name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_libserialport: 0.3.0 # Kept as fixed version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/yariscross.png
    - assets/images/Brake.svg # No longer duplicated
    - assets/images/abs.svg
    - assets/images/Airbag.svg
    - assets/images/Battery.svg
    - assets/images/fuel.svg
    - assets/images/SeatBelt.svg
    - assets/images/background.jpg
    - assets/images/tire_pressure.svg